{{- if .Values.global.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "adot-collector.fullname" . }}
  labels:
    {{- include "adot-collector.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "adot-collector.fullname" . }}
  labels:
    {{- include "adot-collector.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "adot-collector.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace | default "observability" }}
roleRef:
  kind: ClusterRole
  name: {{ include "adot-collector.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
