{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "adot-collector.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace | default "observability" }}
  labels:
    {{- include "adot-collector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
