# Default values for adot-collector
replicaCount: 1

image:
  repository: public.ecr.aws/aws-observability/aws-otel-collector
  tag: v0.40.0
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: adot-collector
  annotations: {}

resources:
  requests:
    cpu: 250m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 1Gi

config:
  scrapeInterval: 30s
  scrapeTimeout: 10s
  logLevel: info

nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 8888
  healthCheckPort: 13133

# AMP configuration
amp:
  endpoint: "https://aps-workspaces.ap-northeast-2.amazonaws.com/workspaces/ws-c4d2c705-3a5c-436c-87b7-70a0e5549559/api/v1/remote_write"
  region: ap-northeast-2
