apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-exporter.fullname" . }}
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    {{- include "mongodb-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mongodb-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "mongodb-exporter.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: mongodb-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9216
              protocol: TCP
          env:
            - name: MONGODB_URI
              value: {{ .Values.mongodb.uri | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.exporter.logLevel | quote }}
          args:
            - --mongodb.uri=$(MONGODB_URI)
            {{- if .Values.exporter.collectAll }}
            - --collect-all
            {{- end }}
            - --log.level={{ .Values.exporter.logLevel }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
