apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-exporter.fullname" . }}
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    {{- include "mongodb-exporter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "mongodb-exporter.selectorLabels" . | nindent 4 }}
